name: ShulkerboxInvsee
main: com.Ting.ShulkerboxInvsee.Main
version: 1.0
api-version: 1.16
description: ShulkerboxInvsee
loadbefore:
  - ProtocolLib
depend:
  - ProtocolLib
  - LangUtils

author: hat, Ting